#\!/bin/bash

echo "Please follow these steps to create and push the Calemai repository:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'Calemai'"
echo "3. Set description: 'Calendar-focused task management iOS app'"
echo "4. Make it Public"
echo "5. DO NOT initialize with README, .gitignore, or license"
echo "6. Click 'Create repository'"
echo ""
echo "Then run this command to push your code:"
echo ""
echo "git push -u origin main"
echo ""
echo "Your repository is ready to push at: /Users/jade/Documents/xCode/Calemai"
echo "Remote is already set to: https://github.com/jadewii/Calemai.git"
